server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: ${ORDER_DB_URI:jdbc:postgresql://localhost:5432/order_db}
    username: ${ORDER_DB_USERNAME:postgres}
    password: ${ORDER_DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lemur-15.cloud-iam.com/auth/realms/cloud-native-ecommerce
          jwk-set-uri: https://lemur-15.cloud-iam.com/auth/realms/cloud-native-ecommerce/protocol/openid-connect/certs
          # issuer-uri: ${JWT_ISSUER_URI:http://localhost:8088/realms/cloud-native-ecommerce}
          # jwk-set-uri: ${JWT_SET_URI:http://localhost:8088/realms/cloud-native-ecommerce/protocol/openid-connect/certs}


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: ecommerce-realm
  resource: order-service
  public-client: false
  bearer-only: true
  principal-attribute: preferred_username

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET}

inventory-service:
  api-key: ${API_KEY}
