- name: Fetch Kubernetes Credentials
  hosts: local
  connection: local
  tasks:
    - name: make executable
      shell: chmod +x ./../scripts/fetch_k8s_creds.sh

    - name: Fetch
      shell: ./../scripts/fetch_k8s_creds.sh