server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: ${CART_DB_URI:jdbc:postgresql://localhost:5432/cart_db}
    username: ${CART_DB_USER:postgres}
    password: ${CART_DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lemur-15.cloud-iam.com/auth/realms/cloud-native-ecommerce
          jwk-set-uri: https://lemur-15.cloud-iam.com/auth/realms/cloud-native-ecommerce/protocol/openid-connect/certs
          # issuer-uri: ${JWT_ISSUER_URI:http://localhost:8088/realms/cloud-native-ecommerce}
          # jwk-set-uri: ${JWT_SET_URI:http://localhost:8088/realms/cloud-native-ecommerce/protocol/openid-connect/certs}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

inventory-service:
  api-key: ${API_KEY}

resilience4j:
  circuitbreaker:
    instances:
      inventoryService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3

springdoc:
  api-docs:
    path: /products/api-docs
  swagger-ui:
    path: /products/swagger-ui.html